require:
  - rubocop-rails
  - rubocop-performance
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'log/**'
    - 'app/channels/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
Metrics:
  Enabled: false
Style:
  Documentation:
    Enabled: false
  FrozenStringLiteralComment:
    Enabled: false
Naming:
  MethodName:
    enabled: false